sudo: required
dist: trusty
services:
  - docker

deploy:
  provider: bintray
  skip_cleanup: true
  file: "packaging/root/${PACKAGE}-${DIST}-${TARGET}/descriptor.json"
  user: "ntadej"
  key:
    secure: "ODJ5nLdypZBP2EZHbp4d7WrW1jzOxdV4psOOTG2BHUqNEePrY5uurWjqQvTysN0c5UDdqkeIhb7qDxh5leyb0l6cisdv+1DGR8Z+CyDdwhYJXtKTEBeqHY5nbvAuSqsVf7SLekSZC2sauTJOU3a3i8Ig1VhqQacSXBGwTw5cv0c="
  on:
    branch: project/travis
    condition: $TRAVIS_OS_NAME = linux

cache: ccache

matrix:
  include:
    - os: linux
      env: DIST=ubuntu TARGET=xenial-amd64 PACKAGE=deb
    - os: linux
      env: DIST=ubuntu TARGET=xenial-i386 PACKAGE=deb

branches:
  except:
    - project/appveyor
    - project/docs

language: cpp

before_install: . scripts/ci/$TRAVIS_OS_NAME/before_install.sh
install: . scripts/ci/$TRAVIS_OS_NAME/install.sh
script: . scripts/ci/$TRAVIS_OS_NAME/script.sh
after_success: . scripts/ci/$TRAVIS_OS_NAME/after_success.sh
